Repository adriens/temps-attente-streamlit, pull requests merged in 2024-10, with the labels that each got.

#30 Ajout menu déroulant communes et agences #21
  app.py
Labels: enhancement

#34 use realAvgWaitingTimeMs field
  app.py
Labels: BUILD

#41 Optimisation usage API (#37)
  app.py
  utils.py
Labels: enhancement, RUN

#42 Ajout idAgence en query parameters
  app.py
  utils.py
Labels: quickfix, RUN

#46 Ajout tooltip sur collapser sidebar
  app.py
Labels: enhancement, quickfix, BUILD

#47 Ajout nom de l'agence
  app.py
Labels: enhancement, quickfix, BUILD

#48 Liste de commune triée #45
  app.py
Labels: quickfix, BUILD

#54 Ajout graphique historique des temps d'attente pour une agence donnée…
  README.md
  app.py
  utils.py
Labels: enhancement, succes-remarquable, BUILD

#55 fix le bug commune #53
  app.py
Labels: bug, quickfix, RUN
