Repository adriens/temps-attente-streamlit, pull requests merged in 2024-09, with the labels that each got.

#13 doc(README) : Def de l'équipe
  README.md
Labels: documentation, quickfix, BUILD

#17 Première page statique : hello opt-nc
  Dockerfile
  README.md
  app.py
  assets/images/logo_opt.png
  assets/images/logo_unc.jpg
  requirements.txt
Labels: enhancement, succes-remarquable, BUILD

#18 doc(Kickoff) : AJout DoD/Definition of Done
  README.md
Labels: documentation, quickfix, BUILD

#25 Clé API dans variable environnement
  README.md
  app.py
  requirements.txt
  utils.py
Labels: enhancement, succes-remarquable, BUILD

#29 Correction fuseau horaire
  utils.py
Labels: quickfix
